# Generated by Django 2.0.5 on 2018-05-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcity', '0004_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playdate',
            name='dogs',
            field=models.ManyToManyField(to='dogcity.Dog'),
        ),
    ]
