# Generated by Django 2.0.5 on 2018-05-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogcity', '0005_playdate_dogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='dog',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='playdate',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
