# Generated by Django 2.0.5 on 2018-05-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcity', '0007_auto_20180530_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
