# Generated by Django 2.0.5 on 2018-05-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcity', '0008_auto_20180530_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walk',
            name='time',
        ),
        migrations.AlterField(
            model_name='walk',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
