# Generated by Django 2.0.5 on 2018-05-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcity', '0009_auto_20180530_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
