# Generated by Django 2.0.5 on 2018-05-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogcity', '0002_auto_20180526_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
    ]
